class CreateLogEntries < ActiveRecord::Migration[5.0]
  def change
    create_table :log_entries do |t|
      t.float :LATITUDE
      t.float :LONGITUDE
      t.datetime :RECEIVED_AT
      t.datetime :RECORDED_AT
      t.string :GPRMC_VALID
      t.integer :GPS_SPEED
      t.integer :GPS_DIR
      t.integer :GPS_ALTITUDE
      t.boolean :DIO_IGNITION
      t.integer :BATT
      t.string :ODO_PARTIAL_KM
      t.integer :ODO_FULL
      t.integer :GPS_PDOP
      t.integer :FMS_FUEL_LEVEL_2
      t.string :AREA_LIST
      t.integer :GPS_FIXED_SAT_NUM
      t.integer :BEHAVE_ID
      t.integer :BEHAVE_LONG
      t.integer :BEHAVE_LAT
      t.integer :BEHAVE_DAY_OF_YEAR
      t.integer :BEHAVE_TIME_OF_DAY
      t.integer :BEHAVE_GPS_SPEED_BEGIN
      t.integer :BEHAVE_GPS_SPEED_PEAK
      t.integer :BEHAVE_GPS_SPEED_END
      t.integer :BEHAVE_GPS_HEADING_BEGIN
      t.integer :BEHAVE_GPS_HEADING_PEAK
      t.integer :BEHAVE_GPS_HEADING_END
      t.integer :BEHAVE_ACC_X_BEGIN
      t.integer :BEHAVE_ACC_X_PEAK
      t.integer :BEHAVE_ACC_X_END
      t.integer :BEHAVE_ACC_Y_BEGIN
      t.integer :BEHAVE_ACC_Y_PEAK
      t.integer :BEHAVE_ACC_Y_END
      t.integer :BEHAVE_ACC_Z_BEGIN
      t.integer :BEHAVE_ACC_Z_PEAK
      t.integer :BEHAVE_ACC_Z_END
      t.integer :BEHAVE_ELAPSED
      t.integer :BEHAVE_UNIQUE_ID
      t.string :MDI_CRASH_DETECTED
      t.string :MDI_OBD_STACK_NAME
      t.string :EVENT
      t.boolean :MDI_EXT_BATT_LOW
      t.integer :MDI_EXT_BATT_VOLTAGE
      t.boolean :MDI_PANIC_STATE
      t.string :MDI_PANIC_MESSAGE
      t.boolean :MDI_DTC_MIL
      t.integer :MDI_DTC_NUMBER
      t.integer :MDI_RPM_MAX
      t.integer :MDI_RPM_MIN
      t.integer :MDI_RPM_AVERAGE
      t.boolean :MDI_RPM_OVER
      t.integer :MDI_RPM_AVERAGE_RANGE_1
      t.integer :MDI_RPM_AVERAGE_RANGE_2
      t.integer :MDI_RPM_AVERAGE_RANGE_3
      t.integer :MDI_RPM_AVERAGE_RANGE_4
      t.string :MDI_SENSORS_RECORDER_DATA
      t.string :MDI_SENSORS_RECORDER_CALIBRATION
      t.integer :ODO_PARTIAL_METER
      t.integer :ODO_FULL_METER
      t.integer :MDI_HEALTH_WRITEDIR_FREE
      t.integer :MDI_HEALTH_OPENED_FDS
      t.integer :MDI_HEALTH_THREADS
      t.integer :MDI_HEALTH_LOADAVG15
      t.integer :MDI_HEALTH_MIN_BATT_TEMP
      t.integer :MDI_HEALTH_MAX_BATT_TEMP
      t.integer :MDI_HEALTH_MIN_CASE_TEMP
      t.integer :MDI_HEALTH_MAX_CASE_TEMP
      t.string :MDI_OBD_PID_1
      t.string :MDI_OBD_PID_2
      t.string :MDI_OBD_PID_3
      t.string :MDI_OBD_PID_4
      t.string :MDI_OBD_PID_5
      t.integer :MDI_DASHBOARD_MILEAGE
      t.integer :MDI_DASHBOARD_FUEL
      t.integer :MDI_DASHBOARD_FUEL_LEVEL
      t.string :MDI_DIAG_1
      t.string :MDI_DIAG_2
      t.string :MDI_DIAG_3
      t.integer :MDI_MAX_RPM_IN_LAST_OVER_RPM
      t.integer :MDI_OBD_MILEAGE_METERS
      t.boolean :MDI_IDLE_STATE
      t.string :MDI_VEHICLE_STATE
      t.integer :MDI_OBD_SPEED
      t.integer :MDI_OBD_RPM
      t.integer :MDI_OBD_FUEL
      t.string :MDI_OBD_VIN
      t.integer :MDI_OBD_MILEAGE
      t.integer :MDI_JOURNEY_TIME
      t.integer :MDI_IDLE_JOURNEY
      t.integer :MDI_DRIVING_JOURNEY
      t.integer :MDI_MAX_SPEED_IN_LAST_OVERSPEED
      t.integer :MDI_OVERSPEED_COUNTER
      t.boolean :MDI_TOW_AWAY
      t.integer :MDI_ODO_JOURNEY
      t.boolean :MDI_OVERSPEED
      t.integer :MDI_MAX_SPEED_JOURNEY
      t.boolean :MDI_JOURNEY_STATE
      t.string :MDI_CUSTOM_PID_1
      t.string :MDI_CUSTOM_PID_2
      t.string :MDI_CUSTOM_PID_3
      t.string :MDI_CUSTOM_PID_4
      t.string :MDI_CUSTOM_PID_5
      t.string :MDI_CUSTOM_PID_6
      t.string :MDI_CUSTOM_PID_7
      t.string :MDI_CUSTOM_PID_8
      t.string :MDI_CUSTOM_PID_9
      t.string :MDI_CUSTOM_PID_10
      t.string :MDI_CUSTOM_PID_11
      t.string :MDI_CUSTOM_PID_12
      t.string :MDI_CUSTOM_PID_13
      t.string :MDI_CUSTOM_PID_14
      t.string :MDI_CUSTOM_PID_15
      t.string :MDI_CUSTOM_PID_16
      t.string :MDI_CUSTOM_PID_17
      t.string :MDI_CUSTOM_PID_18
      t.string :MDI_CUSTOM_PID_19
      t.string :MDI_CUSTOM_PID_20
      t.string :MDI_CUSTOM_PID_21
      t.string :MDI_CUSTOM_PID_22
      t.string :MDI_CUSTOM_PID_23
      t.string :MDI_CUSTOM_PID_24
      t.string :MDI_CUSTOM_PID_25
      t.string :MDI_CUSTOM_PID_26
      t.string :MDI_CUSTOM_PID_27
      t.string :MDI_CUSTOM_PID_28
      t.string :MDI_CUSTOM_PID_29
      t.string :MDI_CUSTOM_PID_30
      t.string :MDI_CUSTOM_PID_31
      t.string :MDI_CUSTOM_PID_32
      t.string :MDI_CUSTOM_PID_33
      t.string :MDI_CUSTOM_PID_34
      t.string :MDI_CUSTOM_PID_35
      t.string :MDI_CUSTOM_PID_36
      t.string :MDI_CUSTOM_PID_37
      t.string :MDI_CUSTOM_PID_38
      t.string :MDI_CUSTOM_PID_39
      t.string :MDI_CUSTOM_PID_40
      t.string :MDI_CUSTOM_PID_41
      t.string :MDI_CUSTOM_PID_42
      t.string :MDI_CUSTOM_PID_43
      t.string :MDI_CUSTOM_PID_44
      t.string :MDI_CUSTOM_PID_45
      t.string :MDI_CUSTOM_PID_46
      t.string :MDI_CUSTOM_PID_47
      t.string :MDI_CUSTOM_PID_48
      t.string :MDI_CUSTOM_PID_49
      t.string :MDI_CUSTOM_PID_50
      t.string :MDI_CC_DTC_LIST
      t.string :ENH_DASHBOARD_MILEAGE
      t.string :ENH_DASHBOARD_FUEL
      t.string :ENH_DASHBOARD_FUEL_LEVEL
      t.string :MDI_CC_OIL_LEVEL
      t.string :MDI_CC_OIL_LEVEL_WARNING_THRESHOLD
      t.string :MDI_CC_OIL_LEVEL_STATUS
      t.string :MDI_CC_TIME_FOR_NEXT_INSPECTION
      t.string :MDI_CC_DISTANCE_FOR_NEXT_INSPECTION
      t.string :MDI_CC_DISTANCE_FOR_CHANGE_OIL
      t.string :MDI_CC_TIME_FOR_CHANGE_OIL

      t.timestamps
    end
  end
end
